# Generated by Django 3.2.5 on 2021-07-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cryptocurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='symbol',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
    ]
