# Generated by Django 3.2.5 on 2021-07-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_cryptocurrency_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instruments',
        ),
    ]
